### ISSUE TITLE
Nicknames in users table with apostrophes cause sign on issues

### ISSUE THREAD

**Issue by chrisgilpin** [curveball/a12n-server#229] opened 2021-02-03 21:36 UTC
I've noticed an issue when an entry in the *users* table -> nickname column has an apostrophe that authentication doesn't work.

Removing the apostrophe from the entry allows the user to sign on.

Example of nickname entry that causes an issue:  Sparky’s Roadside Barbecue 

The error it gives: 
<img width="1483" alt="Screen Shot 2021-02-03 at 4 32 39 PM" src="https://user-images.githubusercontent.com/4729575/106812665-fdaddc00-663d-11eb-9dbb-97b5d10b6109.png">

**Comment by chrisgilpin** [comment] 2021-02-03 21:39
I should note - this is in the *auth* database

**Comment by evert** [comment] 2021-02-03 22:08
I can't reproduce this, so this will probably need some logs to make sure it's really an issue with a12nserver.

We use parameterized queries (just confirmed to be 100% sure), so it can't be a simple escaping issue.

**Comment by evert** [comment] 2021-06-29 03:45
Didn't get more info, so I'm closing. If there's more proof, definitely happy to look into this again!

**Closed by evert** 2021-06-29 03:45 UTC
